
# Configuration file for the Flash C++ documentation generator.
# https://github.com/sapfire-sdk/flash

[project]
name = "Sapfire"
version = "v3.0.0"
repository = "https://github.com/sapfire-sdk/sapfire"
tree = "https://github.com/sapfire-sdk/sapfire/tree/main"
icon = "loader/resources/logos/sapfire-circle.png"

[tutorials]
dir = "docs"
assets = [
    "docs/assets/*.png",
    "docs/assets/handbook/vol1/*.png",
    "docs/assets/handbook/vol2/*.png",
]

[[sources]]
name = "Sapfire"
dir = "loader/include"
include = [
    "Sapfire/**/*.hpp",
    "Sapfire/**/*.h",
]
exclude = [
    "Sapfire/modify/Comparer.hpp",
    "Sapfire/platform/*.hpp",
    "Sapfire/c++stl/*.hpp",
    # All of the relevant cocos headers are included through Sapfire headers
    "Sapfire/cocos/**/*.h"
]

[[sources]]
name = "Bindings"
dir = "build-docs/bindings/bindings"
include = [
    "Sapfire/binding/*.hpp"
]
# Bindings are generated at compile time
exists-online = false

# CMake options

[cmake]
config-args = [
    "-G", "Ninja",
    "-DCMAKE_CXX_COMPILER=Clang",
    "-DCMAKE_C_COMPILER=Clang",
    "-DSAPFIRE_BUILDING_DOCS=On",
    "-DSAPFIRE_PLATFORM_NAME=Win64",
    "-DSAPFIRE_CODEGEN_CMAKE_ARGS=-DCMAKE_CXX_COMPILER=Clang;-DCMAKE_C_COMPILER=Clang",
    "-DWIN32=On"
]
build-dir = "build-docs"

# The file we use to get all the include paths and such
infer-args-from = "loader/src/load.cpp"
