if (NOT DEFINED SAPFIRE_TARGET_PLATFORM)
	if(APPLE)
		if(IOS)
			set(SAPFIRE_TARGET_PLATFORM "iOS")
		else()
			set(SAPFIRE_TARGET_PLATFORM "MacOS")
		endif()
	elseif(WIN32)
		set(SAPFIRE_TARGET_PLATFORM "Win64")
	elseif(ANDROID)
		if (ANDROID_ABI STREQUAL "arm64-v8a")
			set(SAPFIRE_TARGET_PLATFORM "Android64")
		elseif(ANDROID_ABI STREQUAL "armeabi-v7a")
			set(SAPFIRE_TARGET_PLATFORM "Android32")
		endif()
	else()
		message(FATAL_ERROR "Unable to detect platform, please set SAPFIRE_TARGET_PLATFORM in the root CMake file.")
	endif()
endif()